services:
  postgres_16:
    image: "postgres:16"
    container_name: "postgres_16"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "./volumes/postgres_16/data:/var/lib/postgresql/data"
