version: "3.9"
services:

  postgres_13:
    image: "postgres:13"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "./volumes/postgres_13/data:/var/lib/postgresql/data"
