services:
  mysql:
    image: "mysql:8.4"
    container_name: "mysql_8"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - "./volumes/mysql_8/data:/var/lib/mysql"
