version: "3.9"
services:

  mysql_8:
    image: "mysql:8"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - "./volumes/mysql_8/data:/var/lib/mysql"

  mysql_57:
    image: "mysql:5.7"
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - "./volumes/mysql_57/data:/var/lib/mysql"
