services:
  valkey:
    image: "bitnami/valkey:7.2"
    container_name: "valkey"
    ports:
      - "6379:6379"
    volumes:
      - "./volumes/valkey_7_2/data:/bitnami/valkey/data"
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
